version: "3"
services: 
    app:
        build: .
        image: "node_test"
        container_name: "node_test"
        command: npm start
        depends_on:
            - "mongo"
        environment: 
            - "PORT=3000"
        ports:
            - "3000:3000"
        volumes: 
            - "./:/app"
    mongo:
        image: "mongo"
        container_name: "mongo"
        volumes: 
           - "./db./data/db"
